# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "ZMT Creative"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "/"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
copyright = "&copy; {year} ZMT Creative LLC"

############################
## Advanced options below ##
############################

# Name of Academic theme folder in `themes/`.
theme = ["academic-zmtc","academic"]

# Get last modified date for content from Git?
enableGitInfo = true

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
# Set `true` for Chinese/Japanese/Korean languages.
hasCJKLanguage = false
defaultContentLanguageInSubdir = false
# Workaround for https://github.com/gohugoio/hugo/issues/5687
removePathAccents = true

# Number of items per page in paginated lists.
paginate = 10
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

summaryLength = 500

[outputs]
  home = [ "HTML", "RSS", "JSON", "WebAppManifest" ]
  section = [ "HTML", "RSS" ]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
  hrefTargetBlank = true
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  # Anchor for cropping. Options include Smart and Center.
  anchor = "smart"

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]

[services.rss]
  limit = 30
