# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#"
  pre = "<i class='fas fa-home'></i>&nbsp;"
  weight = 10

[[main]]
  name = "Recent<br>Posts"
  url = "#posts"
  pre = "<i class='far fa-newspaper'></i>&nbsp;"
  weight = 20

[[main]]
  name = "Image<br>Gallery"
  url = "/gallery/"
  pre = "<i class='fas fa-images'></i>&nbsp;"
  weight = 30

# [[main]]
#   name = ""
#   identifier = "postpage"
#   url = ""
#   weight = 25

# [[main]]
#   name = "All Posts"
#   url = "/post/"
#   parent = "postpage"
#   weight = 1

# [[main]]
#   name = "Projects"
#   url = "#projects"
#   weight = 30

# [[main]]
#   name = "Publications"
#   url = "#featured"
#   weight = 40

[[main]]
  name = "Popular<br>Categories"
  url = "#categories"
  pre = "<i class='fas fa-folder'></i>&nbsp;"
  weight = 54

[[main]]
  name = "Popular<br>Tags"
  url = "#tags"
  pre = "<i class='fas fa-tags'></i>&nbsp;"
  weight = 55

[[main]]
  name = "Info"
  identifier = "info"
  pre = "<i class='fas fa-info-circle'></i>&nbsp;&nbsp;"
  weight = 60

[[main]]
  name = "About"
  url = "#about"
  weight = 1
  parent = "info"

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 5
  parent = "info"

[[main]]
  name = "FAQ"
  url = "/faq/"
  weight = 7
  parent = "info"

[[main]]
  name = "Privacy Policy"
  url = "/privacy-policy/"
  weight = 10
  parent = "info"

[[main]]
  name = "Terms & Conditions"
  url = "/terms-and-conditions/"
  weight = 15
  parent = "info"


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
