# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#"
  weight = 10

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 20

# [[main]]
#   name = "Projects"
#   url = "#projects"
#   weight = 30

# [[main]]
#   name = "Publications"
#   url = "#featured"
#   weight = 40

[[main]]
  name = "Topics"
  url = "#tags"
  weight = 55

[[main]]
  name = "Info"
  identifier = "info"
  weight = 60

[[main]]
  name = "About"
  url = "#about"
  weight = 1
  parent = "info"

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 5
  parent = "info"

[[main]]
  name = "FAQ"
  url = "/faq/"
  weight = 7
  parent = "info"

[[main]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 10
  parent = "info"

[[main]]
  name = "Terms & Conditions"
  url = "/terms/"
  weight = 15
  parent = "info"


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
